### ISSUE TITLE
Call graph for 1d Ising model crashes

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#682]
Code:
```py
from qualtran.bloqs.qubitization_walk_operator_test import get_walk_operator_for_1d_Ising_model

U = get_walk_operator_for_1d_Ising_model(4, 2e-1)
print(U.call_graph())
```

Error:
```
Traceback (most recent call last):
  File "qualtran/_infra/gate_with_registers.py", line 243, in decompose_bloq
    return Bloq.decompose_bloq(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/_infra/bloq.py", line 146, in decompose_bloq
    return _decompose_from_build_composite_bloq(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/_infra/bloq.py", line 48, in _decompose_from_build_composite_bloq
    out_soqs = bloq.build_composite_bloq(bb=bb, **initial_soqs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/_infra/bloq.py", line 130, in build_composite_bloq
    raise DecomposeNotImplementedError(f"{self} does not declare a decomposition.")
qualtran._infra.bloq.DecomposeNotImplementedError: LessThanEqual(x_bitsize=0, y_bitsize=0) does not declare a decomposition.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(U.call_graph())
          ^^^^^^^^^^^^^^
  File "qualtran/_infra/bloq.py", line 320, in call_graph
    return get_bloq_call_graph(self, generalizer=generalizer, keep=keep, max_depth=max_depth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/resource_counting/bloq_counts.py", line 225, in get_bloq_call_graph
    _build_call_graph(bloq, generalizer, ssa, keep, max_depth, g=g, depth=0)
  File "qualtran/resource_counting/bloq_counts.py", line 136, in _build_call_graph
    _build_call_graph(callee, generalizer, ssa, keep, max_depth, g, depth + 1)
  File "qualtran/resource_counting/bloq_counts.py", line 136, in _build_call_graph
    _build_call_graph(callee, generalizer, ssa, keep, max_depth, g, depth + 1)
  File "qualtran/resource_counting/bloq_counts.py", line 136, in _build_call_graph
    _build_call_graph(callee, generalizer, ssa, keep, max_depth, g, depth + 1)
  File "qualtran/resource_counting/bloq_counts.py", line 120, in _build_call_graph
    callee_counts = _generalize_callees(bloq.build_call_graph(ssa), generalizer)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/_infra/bloq.py", line 288, in build_call_graph
    return self.decompose_bloq().build_call_graph(ssa)
           ^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/_infra/gate_with_registers.py", line 245, in decompose_bloq
    return decompose_from_cirq_style_method(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/cirq_interop/_cirq_to_bloq.py", line 477, in decompose_from_cirq_style_method
    return cirq_optree_to_cbloq(
           ^^^^^^^^^^^^^^^^^^^^^
  File "qualtran/cirq_interop/_cirq_to_bloq.py", line 363, in cirq_optree_to_cbloq
    circuit = cirq.Circuit(optree)
              ^^^^^^^^^^^^^^^^^^^^
  File "cirq/circuits/circuit.py", line 1747, in __init__
    flattened_contents = tuple(ops.flatten_to_ops_or_moments(contents))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cirq/ops/op_tree.py", line 134, in flatten_to_ops_or_moments
    yield from flatten_to_ops_or_moments(subtree)
  File "cirq/ops/op_tree.py", line 133, in flatten_to_ops_or_moments
    for subtree in root:
  File "qualtran/bloqs/arithmetic/comparison.py", line 390, in decompose_from_registers
    lhs, rhs, (target,) = quregs['x'], quregs['y'], quregs['target']
                          ~~~~~~^^^^^
KeyError: 'x'
```

**Comment by tanujkhattar** [comment]
The error is happening because we end up calling comparison gate `LessThanEqual`  with `x_bitsize=0` and `y_bitsize=0`, which is undefined. The right thing to do is to add a check at the call site in state preparation alias sampling and not call the comparison bloq in the decomposition. 

I've sent a PR that fixes it. Feel free to take a look.
