### ISSUE TITLE
`python dev_tools/autogenerate-bloqs-notebooks-v2.py` is broken on main 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#749]
Running `python dev_tools/autogenerate-bloqs-notebooks-v2.py`  gives

```
[toffoli] Replacing Toffoli.call_graph.md cell.
[toffoli] Replacing Toffoli.call_graph.py cell.
[swap_network] Loading existing: /Users/tanujkhattar/quantum/Qualtran/qualtran/bloqs/swap_network.ipynb
Traceback (most recent call last):
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/autogenerate-bloqs-notebooks-v2.py", line 329, in <module>
    render_notebooks()
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/autogenerate-bloqs-notebooks-v2.py", line 312, in render_notebooks
    render_notebook(nbspec)
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 234, in render_notebook
    cells |= {c.cell_id: c for c in get_cells(bds)}
                                    ^^^^^^^^^^^^^^
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 206, in get_cells
    cells += get_example_instances_cells(bloqdoc, cid_prefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 159, in get_example_instances_cells
    return cells + [_get_one_ex_instance_cell(ex, cid_prefix) for ex in examples]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 159, in <listcomp>
    return cells + [_get_one_ex_instance_cell(ex, cid_prefix) for ex in examples]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 145, in _get_one_ex_instance_cell
    text='\n'.join(_get_bloq_example_source_lines(bloq_ex)),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanujkhattar/quantum/Qualtran/dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py", line 85, in _get_bloq_example_source_lines
    raise ValueError(
ValueError: The first line of BloqExample(name='approx_cswap_small', bloq_cls=<class 'qualtran.bloqs.swap_network.CSwapApprox'>, generalizer=[<function cirq_to_bloqs at 0x15a482fc0>, <function ignore_split_join at 0x15a482ca0>, <function ignore_cliffords at 0x15a482f20>, <function generalize_rotation_angle at 0x15a482de0>]) doesn't look like a function definition:     generalizer=[cirq_to_bloqs, ignore_split_join, ignore_cliffords, generalize_rotation_angle]
```

**Comment by mpharrigan** [comment]
This is in the functionality that inspects the source code so we can put code snippets in the jupyter notebooks. The formatter has made the annotation multiple lines, which confuses my rudimentary parsing.
